import type { NativeCapabilityDefinition } from './types'

export const NATIVE_CAPABILITIES: NativeCapabilityDefinition[] = [
  {
    key: 'push_notifications',
    label: 'Push Notifications',
    packageName: 'expo-notifications',
    status: 'enabled',
    platforms: ['ios', 'android'],
    androidPermissions: ['POST_NOTIFICATIONS'],
    usage: ['CareerLift notification center', 'Weekly/job alerts'],
  },
  {
    key: 'location_foreground',
    label: 'Location Access (Foreground)',
    packageName: 'expo-location',
    status: 'enabled',
    platforms: ['ios', 'android'],
    androidPermissions: ['ACCESS_COARSE_LOCATION', 'ACCESS_FINE_LOCATION'],
    iosPermissionKeys: ['NSLocationWhenInUseUsageDescription'],
    usage: ['Onboarding location preference', 'Settings profile GPS autofill'],
  },
  {
    key: 'document_picker',
    label: 'Document Picker',
    packageName: 'expo-document-picker',
    status: 'enabled',
    platforms: ['ios', 'android', 'web'],
    usage: ['Resume upload', 'Cover letter upload', 'LinkedIn kit input'],
  },
  {
    key: 'media_library',
    label: 'Media Library',
    packageName: 'expo-image-picker',
    status: 'enabled',
    platforms: ['ios', 'android', 'web'],
    iosPermissionKeys: ['NSPhotoLibraryUsageDescription'],
    usage: ['Image selection for AI image generation'],
  },
  {
    key: 'camera_capture',
    label: 'Camera Capture',
    packageName: 'expo-camera / expo-image-picker',
    status: 'planned',
    platforms: ['ios', 'android'],
    androidPermissions: ['CAMERA'],
    iosPermissionKeys: ['NSCameraUsageDescription'],
    usage: ['Future: capture resume/photo directly from camera'],
    notes: 'Permission/request service is scaffolded under src/native/permissions/media.ts.',
  },
  {
    key: 'microphone_recording',
    label: 'Microphone Recording',
    packageName: 'expo-audio',
    status: 'enabled',
    platforms: ['ios', 'android'],
    androidPermissions: ['RECORD_AUDIO'],
    iosPermissionKeys: ['NSMicrophoneUsageDescription'],
    usage: ['Mock interview recording'],
  },
  {
    key: 'speech_synthesis',
    label: 'Text To Speech',
    packageName: 'expo-speech',
    status: 'enabled',
    platforms: ['ios', 'android', 'web'],
    usage: ['Interview question narration'],
  },
  {
    key: 'clipboard',
    label: 'Clipboard',
    packageName: 'expo-clipboard',
    status: 'enabled',
    platforms: ['ios', 'android', 'web'],
    usage: ['Copy outreach text', 'Copy JD/application snippets'],
  },
  {
    key: 'biometric_auth',
    label: 'Biometric Authentication',
    packageName: 'expo-local-authentication',
    status: 'partial',
    platforms: ['ios', 'android'],
    androidPermissions: ['USE_BIOMETRIC', 'USE_FINGERPRINT'],
    iosPermissionKeys: ['NSFaceIDUsageDescription'],
    usage: ['Account security Face ID / biometric toggle'],
    notes: 'Helper uses runtime module detection so app remains stable if package is missing.',
  },
]
